@startuml

Class TicTacToePage {
    -stateView: StateView
    -squareListView: SquareListView

    override template(): html
}

Class StateView {
    +initPlayer: TPlayer
    +changeState(currentPlayer: TPlayer): void
}
Class SquareListView {
    -state: ITicTacToeState
    +props changeCurrentPlayer: StateView.changeState

    +resetState(): void

    -@on('click', 'square')
    -isEndGame(): void
    -setIsEndGame(isEndGame:boolean): void
    -updateSquares(): void
    -setCurrentPlayer(): void
    -isExists(): void
    -isWin(): void
    -isDraw(): void
}

Class ResetButtonView {
    +props reset: SquareListView.resetState

    -@on('click'): void
}


TicTacToePage <|-- StateView
TicTacToePage <|-- SquareListView
TicTacToePage <|-- ResetButtonView

StateView - SquareListView : +changeState(currentPlayer: TPlayer): void >
SquareListView - ResetButtonView : +resetState(): void >




@enduml