@startuml

Class TicTacToePage<Props> {
    -stateView: StateView
    -squareListView: SquareListView

    +override template(Props): html
}

Class StateView<Props> {
    +initPlayer: TPlayer
    +changeState(currentPlayer: TPlayer): void

    +override template(Props): html
}
Class SquareListView<Props> {
    -state: ITicTacToeState
    +props changeCurrentPlayer: StateView.changeState

    +resetState(): void

    -@on('click', 'square')
    -isEndGame(): void
    -setIsEndGame(isEndGame:boolean): void
    -updateSquares(): void
    -setCurrentPlayer(): void
    -isExists(): void
    -isWin(): void
    -isDraw(): void

    +override template(Props): html
}

Class ResetButtonView<Props> {
    +props reset: SquareListView.resetState

    -@on('click'): void

    +override template(Props): html
}

Class ButtonDefault<Props> {
    +props label: string;
    +props color: string
    +props variant: ButtonType
    +props size: ButtonSize
    +props radius: ButtonSize
    +onClick?: () => void

    +override onMount(): void
    +override template(Props): html
}


TicTacToePage <|-- StateView
TicTacToePage <|-- SquareListView
TicTacToePage <|-- ResetButtonView

ResetButtonView <|-- ButtonDefault

StateView - SquareListView : +changeState(currentPlayer: TPlayer): void >
SquareListView - ResetButtonView : +resetState(): void >




@enduml